services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7.4

  mongofalcone:
    image: mongo
    restart: always
    container_name: mongofalcone
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=falcon
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_PASSWORD=Falconerocks
    volumes:
      - ./mongo_data/:/data/db/

volumes:
  mongo_data: